/**
 * Centralized error code registry.
 * Backend always returns { code, error } — frontend maps code → i18n key.
 */

const ErrorCodes = Object.freeze({
  // Validation (400)
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NO_FILE_UPLOADED: 'NO_FILE_UPLOADED',
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
  FILE_EMPTY: 'FILE_EMPTY',

  // Extraction (400)
  PDF_EXTRACTION_FAILED: 'PDF_EXTRACTION_FAILED',
  DOCX_EXTRACTION_FAILED: 'DOCX_EXTRACTION_FAILED',

  // Auth (401/403)
  AUTH_REQUIRED: 'AUTH_REQUIRED',

  // Rate limit (429)
  RATE_LIMITED: 'RATE_LIMITED',

  // LLM upstream (502 / 400)
  LLM_UPSTREAM_ERROR: 'LLM_UPSTREAM_ERROR',
  LLM_BAD_REQUEST: 'LLM_BAD_REQUEST', // 4xx from LiteLLM — carries user-readable detail in `detail` field
  LLM_EMPTY_RESPONSE: 'LLM_EMPTY_RESPONSE',
  LLM_INVALID_JSON: 'LLM_INVALID_JSON',
  LLM_NO_CHOICES: 'LLM_NO_CHOICES',
  LLM_CONTENT_FILTERED: 'LLM_CONTENT_FILTERED',

  // Timeout (504)
  LLM_TIMEOUT: 'LLM_TIMEOUT',
  IMAGE_TIMEOUT: 'IMAGE_TIMEOUT',

  // Chart extraction (400/404/500)
  CHART_IMAGE_NOT_FOUND: 'CHART_IMAGE_NOT_FOUND',
  CHART_EXTRACTION_FAILED: 'CHART_EXTRACTION_FAILED',

  // Feedback (400)
  FEEDBACK_MISSING_FIELDS: 'FEEDBACK_MISSING_FIELDS',

  // Files proxy (400/502)
  FILE_NO_ID_RETURNED: 'FILE_NO_ID_RETURNED',

  // Logs (400)
  LOGS_INVALID_ENTRIES: 'LOGS_INVALID_ENTRIES',
  LOGS_TOO_MANY_ENTRIES: 'LOGS_TOO_MANY_ENTRIES',

  // Icons (400/404/502)
  ICON_QUERY_REQUIRED: 'ICON_QUERY_REQUIRED',
  ICON_NOT_FOUND: 'ICON_NOT_FOUND',
  ICON_FETCH_FAILED: 'ICON_FETCH_FAILED',

  // Server (500)
  INTERNAL_ERROR: 'INTERNAL_ERROR',
})

export { ErrorCodes }
