export const localStorageKey = {
  localLanguage: 'localLanguage',
  excelFormulaLanguage: 'excelFormulaLanguage',
  insertType: 'insertType',
  useWordFormatting: 'useWordFormatting',
  useSelectedText: 'useSelectedText',
  agentMaxIterations: 'agentMaxIterations',
  threadId: 'threadId',
  modelTier: 'modelTier',
  userGender: 'userGender',
  userFirstName: 'userFirstName',
  userLastName: 'userLastName',
  darkMode: 'darkMode',
  litellmUserKey: 'litellmUserKey',
  litellmUserEmail: 'litellmUserEmail',
  rememberCredentials: 'rememberCredentials',
} as const
